// <auto-generated />
namespace Incubadora_Ideas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Pessoal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pessoal));
        
        string IMigrationMetadata.Id
        {
            get { return "201505271007134_Pessoal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
